### PR TITLE
Latest master from upstream

### PR DESCRIPTION
**Pull request by pombredanne**

### CODE REVIEW

**Comment by pombredanne** [comment]
@JoshData Thanks!

**Comment by JoshData** [comment]
Any particular reason you're maintaining a fork?

**Comment by pombredanne** [comment]
@JoshData I always maintain forks of the code I use or plan to use.  Unfortunately (which may not be your case) repos come and go and sometimes are plain deleted or relicensed which then creates some havoc...

**Comment by JoshData** [comment]
Makes sense. Just curious. :)

**Pull request merged**
